[project]
name = 'walter-token'
description = 'A token made by Walter'
authors = ['Walter Nwaugo']
telemetry = true
cache_dir = '.\.cache'
[contracts.walterToken]
path = ['contracts/walterToken.clar', 'contracts/sendMany.clar']
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']
[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
enable_hints = true




